# Build Geth in a stock Go builder container
FROM golang:1.11-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers

ADD . /go-blockchain
RUN cd /go-blockchain && make all

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /go-blockchain/build/bin/* /usr/local/bin/

EXPOSE 8545 8546 40404 40404/udp
